# Generated by Django 5.2.8 on 2025-12-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reponse_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='feed.message'),
        ),
    ]
